### ISSUE TITLE
Disable vertical scrolling for ...

### ISSUE THREAD

**Issue by buckle2000** [itchio/itch.io#662]
On Firefox and newest IE...
If you go to any developer page like [this page](https://leafo.itch.io/) and scroll to the bottom, you will see this ungly vertical scroll bar: ![default](https://user-images.githubusercontent.com/10850402/27342313-6e2af138-5612-11e7-8825-1bdad64250aa.PNG)

So can anyone add `overflow-y: hidden` to the element?

**Comment by bjorn** [comment]
Can't reproduce on Firefox 56.0.2 on Linux. Has this been fixed in the meantime?

**Comment by buckle2000** [comment]
![default](https://user-images.githubusercontent.com/10850402/32831736-3ee18784-ca34-11e7-89ec-9c5d3e43513d.png)
![default](https://user-images.githubusercontent.com/10850402/32831744-452849d4-ca34-11e7-8e2c-a0a4bcb557aa.png)
No it's not fixed.

**Comment by buckle2000** [comment]
Well, the fix should be easy.
Just change `overflow: scroll` to `overflow-x: auto`.

**Comment by buckle2000** [comment]
Also, I think it is not a big deal to open source the itch.io website (frontend), since it's already "open source" by definition~
